{-# LANGUAGE CPP #-}
module Control.Instances.GHC_Packages () where

import Control.Instances.Package.Array ()
import Control.Instances.Package.Base ()
import Control.Instances.Package.Binary ()
import Control.Instances.Package.Bytestring ()
import Control.Instances.Package.Cabal ()
import Control.Instances.Package.Containers ()
import Control.Instances.Package.Deepseq ()
import Control.Instances.Package.Directory ()
import Control.Instances.Package.Filepath ()
import Control.Instances.Package.Ghc ()
import Control.Instances.Package.Ghc_boot ()
import Control.Instances.Package.Ghc_compact ()
import Control.Instances.Package.Ghc_prim ()
import Control.Instances.Package.Hoopl ()
import Control.Instances.Package.Hpc ()
import Control.Instances.Package.Integer_gmp ()
import Control.Instances.Package.Process ()
import Control.Instances.Package.Template_haskell ()
import Control.Instances.Package.Time ()
import Control.Instances.Package.Unix ()
import Control.Instances.Package.Win32 ()
