{-# LANGUAGE CPP #-}
module Control.Instances.Package.Array () where
#ifdef MIN_VERSION_array
#if MIN_VERSION_array(0,5,2)
import Data.Array ()
import Data.Array.Base ()
import Data.Array.IArray ()
import Data.Array.IO ()
import Data.Array.IO.Safe ()
import Data.Array.IO.Internals ()
import Data.Array.MArray ()
import Data.Array.MArray.Safe ()
import Data.Array.ST ()
import Data.Array.ST.Safe ()
import Data.Array.Storable ()
import Data.Array.Storable.Safe ()
import Data.Array.Storable.Internals ()
import Data.Array.Unboxed ()
import Data.Array.Unsafe ()
#elif MIN_VERSION_array(0,5,1)
import Data.Array ()
import Data.Array.Base ()
import Data.Array.IArray ()
import Data.Array.IO ()
import Data.Array.IO.Safe ()
import Data.Array.IO.Internals ()
import Data.Array.MArray ()
import Data.Array.MArray.Safe ()
import Data.Array.ST ()
import Data.Array.ST.Safe ()
import Data.Array.Storable ()
import Data.Array.Storable.Safe ()
import Data.Array.Storable.Internals ()
import Data.Array.Unboxed ()
import Data.Array.Unsafe ()
#elif MIN_VERSION_array(0,5,1)
import Data.Array ()
import Data.Array.Base ()
import Data.Array.IArray ()
import Data.Array.IO ()
import Data.Array.IO.Safe ()
import Data.Array.IO.Internals ()
import Data.Array.MArray ()
import Data.Array.MArray.Safe ()
import Data.Array.ST ()
import Data.Array.ST.Safe ()
import Data.Array.Storable ()
import Data.Array.Storable.Safe ()
import Data.Array.Storable.Internals ()
import Data.Array.Unboxed ()
import Data.Array.Unsafe ()
#elif MIN_VERSION_array(0,5,0)
import Data.Array ()
import Data.Array.Base ()
import Data.Array.IArray ()
import Data.Array.IO ()
import Data.Array.IO.Safe ()
import Data.Array.IO.Internals ()
import Data.Array.MArray ()
import Data.Array.MArray.Safe ()
import Data.Array.ST ()
import Data.Array.ST.Safe ()
import Data.Array.Storable ()
import Data.Array.Storable.Safe ()
import Data.Array.Storable.Internals ()
import Data.Array.Unboxed ()
import Data.Array.Unsafe ()
#elif MIN_VERSION_array(0,4,0)
import Data.Array ()
#elif MIN_VERSION_array(0,4,0)
import Data.Array ()
#elif MIN_VERSION_array(0,3,0)
import Data.Array ()
#elif MIN_VERSION_array(0,3,0)
import Data.Array ()
#elif MIN_VERSION_array(0,3,0)
import Data.Array ()
#elif MIN_VERSION_array(0,3,0)
import Data.Array ()
#elif MIN_VERSION_array(0,2,0)
import Data.Array ()
#elif MIN_VERSION_array(0,1,0)
import Data.Array ()
import Data.Array.Base ()
import Data.Array.Diff ()
import Data.Array.IArray ()
import Data.Array.IO ()
import Data.Array.MArray ()
import Data.Array.ST ()
import Data.Array.Storable ()
import Data.Array.Unboxed ()
#endif
#endif