{-# LANGUAGE CPP #-}
module Control.Instances.Package.Binary () where
#ifdef MIN_VERSION_binary
#if MIN_VERSION_binary(0,9,0)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
#elif MIN_VERSION_binary(0,8,5)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
#elif MIN_VERSION_binary(0,8,5)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
#elif MIN_VERSION_binary(0,8,4)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
#elif MIN_VERSION_binary(0,8,4)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
#elif MIN_VERSION_binary(0,8,3)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
#elif MIN_VERSION_binary(0,8,2)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,8,2)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,8,1)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,8,0)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,8,0)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,7,6)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,7,6)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,7,5)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,7,4)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,7,3)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,7,2)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,7,2)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,7,2)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,7,2)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,7,1)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,7,0)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,7,0)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,6,4)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,6,3)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,6,2)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,6,1)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,6,0)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Get.Internal ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,5,1)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,5,1)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Builder ()
import Data.Binary.Builder.Internal ()
#elif MIN_VERSION_binary(0,5,0)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Builder ()
#elif MIN_VERSION_binary(0,5,0)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Builder ()
#elif MIN_VERSION_binary(0,5,0)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Builder ()
#elif MIN_VERSION_binary(0,4,5)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Builder ()
#elif MIN_VERSION_binary(0,4,4)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Builder ()
#elif MIN_VERSION_binary(0,4,3)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Builder ()
#elif MIN_VERSION_binary(0,4,3)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Builder ()
#elif MIN_VERSION_binary(0,4,2)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Builder ()
#elif MIN_VERSION_binary(0,4,1)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Builder ()
#elif MIN_VERSION_binary(0,4,0)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Builder ()
#elif MIN_VERSION_binary(0,3,0)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Builder ()
#elif MIN_VERSION_binary(0,2,0)
import Data.Binary ()
import Data.Binary.Put ()
import Data.Binary.Get ()
import Data.Binary.Builder ()
#endif
#endif