{-# LANGUAGE CPP #-}
module Control.Instances.Package.Deepseq () where
#ifdef MIN_VERSION_deepseq
#if MIN_VERSION_deepseq(1,4,3)
import Control.DeepSeq ()
#elif MIN_VERSION_deepseq(1,4,2)
import Control.DeepSeq ()
#elif MIN_VERSION_deepseq(1,4,1)
import Control.DeepSeq ()
#elif MIN_VERSION_deepseq(1,4,1)
import Control.DeepSeq ()
#elif MIN_VERSION_deepseq(1,4,1)
import Control.DeepSeq ()
#elif MIN_VERSION_deepseq(1,4,0)
import Control.DeepSeq ()
#elif MIN_VERSION_deepseq(1,3,0)
import Control.DeepSeq ()
#elif MIN_VERSION_deepseq(1,3,0)
import Control.DeepSeq ()
#elif MIN_VERSION_deepseq(1,3,0)
import Control.DeepSeq ()
#elif MIN_VERSION_deepseq(1,2,0)
import Control.DeepSeq ()
#elif MIN_VERSION_deepseq(1,2,0)
import Control.DeepSeq ()
#elif MIN_VERSION_deepseq(1,1,0)
import Control.DeepSeq ()
#elif MIN_VERSION_deepseq(1,1,0)
import Control.DeepSeq ()
#elif MIN_VERSION_deepseq(1,1,0)
import Control.DeepSeq ()
#elif MIN_VERSION_deepseq(1,0,0)
import Control.DeepSeq ()
#endif
#endif