{-# LANGUAGE CPP #-}
module Control.Instances.Package.Directory () where
#ifdef MIN_VERSION_directory
#if MIN_VERSION_directory(1,3,1)
import System.Directory ()
import System.Directory.Internal ()
import System.Directory.Internal.Prelude ()
#elif MIN_VERSION_directory(1,3,1)
import System.Directory ()
import System.Directory.Internal ()
import System.Directory.Internal.Prelude ()
#elif MIN_VERSION_directory(1,3,1)
import System.Directory ()
import System.Directory.Internal ()
import System.Directory.Internal.Prelude ()
#elif MIN_VERSION_directory(1,3,1)
import System.Directory ()
import System.Directory.Internal ()
import System.Directory.Internal.Prelude ()
#elif MIN_VERSION_directory(1,3,1)
import System.Directory ()
import System.Directory.Internal ()
import System.Directory.Internal.Prelude ()
#elif MIN_VERSION_directory(1,3,1)
import System.Directory ()
import System.Directory.Internal ()
import System.Directory.Internal.Prelude ()
#elif MIN_VERSION_directory(1,3,0)
import System.Directory ()
import System.Directory.Internal ()
import System.Directory.Internal.Prelude ()
#elif MIN_VERSION_directory(1,3,0)
import System.Directory ()
import System.Directory.Internal ()
import System.Directory.Internal.Prelude ()
#elif MIN_VERSION_directory(1,3,0)
import System.Directory ()
import System.Directory.Internal ()
import System.Directory.Internal.Prelude ()
#elif MIN_VERSION_directory(1,2,7)
import System.Directory ()
#elif MIN_VERSION_directory(1,2,7)
import System.Directory ()
#elif MIN_VERSION_directory(1,2,6)
import System.Directory ()
#elif MIN_VERSION_directory(1,2,6)
import System.Directory ()
#elif MIN_VERSION_directory(1,2,6)
import System.Directory ()
#elif MIN_VERSION_directory(1,2,5)
import System.Directory ()
#elif MIN_VERSION_directory(1,2,5)
import System.Directory ()
#elif MIN_VERSION_directory(1,2,4)
import System.Directory ()
#elif MIN_VERSION_directory(1,2,3)
import System.Directory ()
#elif MIN_VERSION_directory(1,2,3)
import System.Directory ()
#elif MIN_VERSION_directory(1,2,2)
import System.Directory ()
#elif MIN_VERSION_directory(1,2,2)
import System.Directory ()
#elif MIN_VERSION_directory(1,2,1)
import System.Directory ()
#elif MIN_VERSION_directory(1,2,0)
import System.Directory ()
#elif MIN_VERSION_directory(1,2,0)
import System.Directory ()
#elif MIN_VERSION_directory(1,1,0)
import System.Directory ()
#elif MIN_VERSION_directory(1,1,0)
import System.Directory ()
#elif MIN_VERSION_directory(1,1,0)
import System.Directory ()
#elif MIN_VERSION_directory(1,0,1)
import System.Directory ()
#elif MIN_VERSION_directory(1,0,1)
import System.Directory ()
#elif MIN_VERSION_directory(1,0,1)
import System.Directory ()
#elif MIN_VERSION_directory(1,0,0)
import System.Directory ()
#elif MIN_VERSION_directory(1,0,0)
import System.Directory ()
#endif
#endif