{-# LANGUAGE CPP #-}
module Control.Instances.Package.Filepath () where
#ifdef MIN_VERSION_filepath
#if MIN_VERSION_filepath(1,4,1)
import System.FilePath ()
import System.FilePath.Posix ()
import System.FilePath.Windows ()
#elif MIN_VERSION_filepath(1,4,1)
import System.FilePath ()
import System.FilePath.Posix ()
import System.FilePath.Windows ()
#elif MIN_VERSION_filepath(1,4,1)
import System.FilePath ()
import System.FilePath.Posix ()
import System.FilePath.Windows ()
#elif MIN_VERSION_filepath(1,4,0)
import System.FilePath ()
import System.FilePath.Posix ()
import System.FilePath.Windows ()
#elif MIN_VERSION_filepath(1,3,0)
import System.FilePath ()
import System.FilePath.Posix ()
import System.FilePath.Windows ()
#elif MIN_VERSION_filepath(1,3,0)
import System.FilePath ()
import System.FilePath.Posix ()
import System.FilePath.Windows ()
#elif MIN_VERSION_filepath(1,3,0)
import System.FilePath ()
import System.FilePath.Posix ()
import System.FilePath.Windows ()
#elif MIN_VERSION_filepath(1,2,0)
import System.FilePath ()
import System.FilePath.Posix ()
import System.FilePath.Windows ()
#elif MIN_VERSION_filepath(1,2,0)
import System.FilePath ()
import System.FilePath.Posix ()
import System.FilePath.Windows ()
#elif MIN_VERSION_filepath(1,1,0)
import System.FilePath ()
import System.FilePath.Posix ()
import System.FilePath.Windows ()
#elif MIN_VERSION_filepath(1,1,0)
import System.FilePath ()
import System.FilePath.Posix ()
import System.FilePath.Windows ()
#elif MIN_VERSION_filepath(1,1,0)
import System.FilePath ()
import System.FilePath.Posix ()
import System.FilePath.Windows ()
#elif MIN_VERSION_filepath(1,1,0)
import System.FilePath ()
import System.FilePath.Posix ()
import System.FilePath.Windows ()
#elif MIN_VERSION_filepath(1,1,0)
import System.FilePath ()
import System.FilePath.Posix ()
import System.FilePath.Windows ()
#elif MIN_VERSION_filepath(1,0,0)
import System.FilePath ()
import System.FilePath.Posix ()
import System.FilePath.Windows ()
#endif
#endif