{-# LANGUAGE CPP #-}
module Control.Instances.Package.Hoopl () where
#ifdef MIN_VERSION_hoopl
#if MIN_VERSION_hoopl(3,10,2)
import Compiler.Hoopl ()
import Compiler.Hoopl.Internals ()
import Compiler.Hoopl.Wrappers ()
import Compiler.Hoopl.Passes.Dominator ()
import Compiler.Hoopl.Passes.DList ()
#elif MIN_VERSION_hoopl(3,10,2)
import Compiler.Hoopl ()
import Compiler.Hoopl.Internals ()
import Compiler.Hoopl.Wrappers ()
import Compiler.Hoopl.Passes.Dominator ()
import Compiler.Hoopl.Passes.DList ()
#elif MIN_VERSION_hoopl(3,10,2)
import Compiler.Hoopl ()
import Compiler.Hoopl.Internals ()
import Compiler.Hoopl.Wrappers ()
import Compiler.Hoopl.Passes.Dominator ()
import Compiler.Hoopl.Passes.DList ()
#elif MIN_VERSION_hoopl(3,10,1)
import Compiler.Hoopl ()
import Compiler.Hoopl.Internals ()
import Compiler.Hoopl.Wrappers ()
import Compiler.Hoopl.Passes.Dominator ()
import Compiler.Hoopl.Passes.DList ()
#elif MIN_VERSION_hoopl(3,10,0)
import Compiler.Hoopl ()
import Compiler.Hoopl.Internals ()
import Compiler.Hoopl.Wrappers ()
import Compiler.Hoopl.Passes.Dominator ()
import Compiler.Hoopl.Passes.DList ()
#elif MIN_VERSION_hoopl(3,10,0)
import Compiler.Hoopl ()
import Compiler.Hoopl.Internals ()
import Compiler.Hoopl.Wrappers ()
import Compiler.Hoopl.Passes.Dominator ()
import Compiler.Hoopl.Passes.DList ()
#elif MIN_VERSION_hoopl(3,10,0)
import Compiler.Hoopl ()
import Compiler.Hoopl.Internals ()
import Compiler.Hoopl.Wrappers ()
import Compiler.Hoopl.Passes.Dominator ()
import Compiler.Hoopl.Passes.DList ()
#elif MIN_VERSION_hoopl(3,9,0)
import Compiler.Hoopl ()
import Compiler.Hoopl.Internals ()
import Compiler.Hoopl.Wrappers ()
import Compiler.Hoopl.Passes.Dominator ()
import Compiler.Hoopl.Passes.DList ()
#elif MIN_VERSION_hoopl(3,8,7)
import Compiler.Hoopl ()
import Compiler.Hoopl.Wrappers ()
import Compiler.Hoopl.Passes.Dominator ()
import Compiler.Hoopl.Passes.DList ()
import Compiler.Hoopl.GHC ()
#elif MIN_VERSION_hoopl(3,8,7)
import Compiler.Hoopl ()
import Compiler.Hoopl.Wrappers ()
import Compiler.Hoopl.Passes.Dominator ()
import Compiler.Hoopl.Passes.DList ()
import Compiler.Hoopl.GHC ()
#elif MIN_VERSION_hoopl(3,8,7)
import Compiler.Hoopl ()
import Compiler.Hoopl.Wrappers ()
import Compiler.Hoopl.Passes.Dominator ()
import Compiler.Hoopl.Passes.DList ()
import Compiler.Hoopl.GHC ()
#elif MIN_VERSION_hoopl(3,8,7)
import Compiler.Hoopl ()
import Compiler.Hoopl.Wrappers ()
import Compiler.Hoopl.Passes.Dominator ()
import Compiler.Hoopl.Passes.DList ()
import Compiler.Hoopl.GHC ()
#elif MIN_VERSION_hoopl(3,8,6)
import Compiler.Hoopl ()
import Compiler.Hoopl.Wrappers ()
import Compiler.Hoopl.Passes.Dominator ()
import Compiler.Hoopl.Passes.DList ()
import Compiler.Hoopl.GHC ()
#elif MIN_VERSION_hoopl(3,8,3)
import Compiler.Hoopl ()
import Compiler.Hoopl.Passes.Dominator ()
import Compiler.Hoopl.Passes.DList ()
import Compiler.Hoopl.GHC ()
#elif MIN_VERSION_hoopl(3,7,12)
import Compiler.Hoopl ()
import Compiler.Hoopl.Zipper ()
import Compiler.Hoopl.ZipDataflowNoRG ()
#elif MIN_VERSION_hoopl(3,7,8)
import Compiler.Hoopl ()
#elif MIN_VERSION_hoopl(3,7,7)
import Compiler.Hoopl ()
#elif MIN_VERSION_hoopl(3,7,4)
import Compiler.Hoopl ()
import Compiler.Hoopl.Dataflow ()
import Compiler.Hoopl.Graph ()
import Compiler.Hoopl.MkGraph ()
import Compiler.Hoopl.Fuel ()
import Compiler.Hoopl.Label ()
#elif MIN_VERSION_hoopl(3,7,3)
import Compiler.Hoopl ()
import Compiler.Hoopl.Dataflow ()
import Compiler.Hoopl.Graph ()
import Compiler.Hoopl.MkGraph ()
import Compiler.Hoopl.Fuel ()
import Compiler.Hoopl.Label ()
#elif MIN_VERSION_hoopl(3,7,3)
import Compiler.Hoopl ()
import Compiler.Hoopl.Dataflow ()
import Compiler.Hoopl.Graph ()
import Compiler.Hoopl.MkGraph ()
import Compiler.Hoopl.Fuel ()
import Compiler.Hoopl.Label ()
#elif MIN_VERSION_hoopl(3,7,3)
import Compiler.Hoopl ()
import Compiler.Hoopl.Dataflow ()
import Compiler.Hoopl.Graph ()
import Compiler.Hoopl.MkGraph ()
import Compiler.Hoopl.Fuel ()
import Compiler.Hoopl.Label ()
#elif MIN_VERSION_hoopl(3,7,2)
import Compiler.Hoopl ()
import Compiler.Hoopl.Dataflow ()
import Compiler.Hoopl.Graph ()
import Compiler.Hoopl.MkGraph ()
import Compiler.Hoopl.Fuel ()
import Compiler.Hoopl.Label ()
#elif MIN_VERSION_hoopl(3,7,1)
import Compiler.Hoopl ()
import Compiler.Hoopl.Dataflow ()
import Compiler.Hoopl.Graph ()
import Compiler.Hoopl.MkGraph ()
import Compiler.Hoopl.Fuel ()
import Compiler.Hoopl.Label ()
#elif MIN_VERSION_hoopl(3,7,0)
import Compiler.Hoopl ()
import Compiler.Hoopl.Dataflow ()
import Compiler.Hoopl.Graph ()
import Compiler.Hoopl.GraphUtil ()
import Compiler.Hoopl.MkGraph ()
import Compiler.Hoopl.Fuel ()
import Compiler.Hoopl.Label ()
#endif
#endif