{-# LANGUAGE CPP #-}
module Control.Instances.Package.Hpc () where
#ifdef MIN_VERSION_hpc
#if MIN_VERSION_hpc(0,6,0)
import Trace.Hpc.Util ()
import Trace.Hpc.Mix ()
import Trace.Hpc.Tix ()
import Trace.Hpc.Reflect ()
#elif MIN_VERSION_hpc(0,6,0)
import Trace.Hpc.Util ()
import Trace.Hpc.Mix ()
import Trace.Hpc.Tix ()
import Trace.Hpc.Reflect ()
#elif MIN_VERSION_hpc(0,6,0)
import Trace.Hpc.Util ()
import Trace.Hpc.Mix ()
import Trace.Hpc.Tix ()
import Trace.Hpc.Reflect ()
#elif MIN_VERSION_hpc(0,6,0)
import Trace.Hpc.Util ()
import Trace.Hpc.Mix ()
import Trace.Hpc.Tix ()
import Trace.Hpc.Reflect ()
#elif MIN_VERSION_hpc(0,5,1)
import Trace.Hpc.Util ()
import Trace.Hpc.Mix ()
import Trace.Hpc.Tix ()
import Trace.Hpc.Reflect ()
#elif MIN_VERSION_hpc(0,5,1)
import Trace.Hpc.Util ()
import Trace.Hpc.Mix ()
import Trace.Hpc.Tix ()
import Trace.Hpc.Reflect ()
#elif MIN_VERSION_hpc(0,5,0)
import Trace.Hpc.Util ()
import Trace.Hpc.Mix ()
import Trace.Hpc.Tix ()
import Trace.Hpc.Reflect ()
#elif MIN_VERSION_hpc(0,5,0)
import Trace.Hpc.Util ()
import Trace.Hpc.Mix ()
import Trace.Hpc.Tix ()
import Trace.Hpc.Reflect ()
#elif MIN_VERSION_hpc(0,5,0)
import Trace.Hpc.Util ()
import Trace.Hpc.Mix ()
import Trace.Hpc.Tix ()
import Trace.Hpc.Reflect ()
#elif MIN_VERSION_hpc(0,5,0)
import Trace.Hpc.Util ()
import Trace.Hpc.Mix ()
import Trace.Hpc.Tix ()
import Trace.Hpc.Reflect ()
#elif MIN_VERSION_hpc(0,5,0)
import Trace.Hpc.Util ()
import Trace.Hpc.Mix ()
import Trace.Hpc.Tix ()
import Trace.Hpc.Reflect ()
#elif MIN_VERSION_hpc(0,5,0)
import Trace.Hpc.Util ()
import Trace.Hpc.Mix ()
import Trace.Hpc.Tix ()
import Trace.Hpc.Reflect ()
#elif MIN_VERSION_hpc(0,5,0)
import Trace.Hpc.Util ()
import Trace.Hpc.Mix ()
import Trace.Hpc.Tix ()
import Trace.Hpc.Reflect ()
#endif
#endif