{-# LANGUAGE CPP #-}
module Control.Instances.Package.Template_haskell () where
#ifdef MIN_VERSION_template_haskell
#if MIN_VERSION_template_haskell(2,12,0)
import Language.Haskell.TH ()
import Language.Haskell.TH.Lib ()
import Language.Haskell.TH.Ppr ()
import Language.Haskell.TH.PprLib ()
import Language.Haskell.TH.Quote ()
import Language.Haskell.TH.Syntax ()
import Language.Haskell.TH.LanguageExtensions ()
#elif MIN_VERSION_template_haskell(2,11,1)
import Language.Haskell.TH ()
import Language.Haskell.TH.Lib ()
import Language.Haskell.TH.Ppr ()
import Language.Haskell.TH.PprLib ()
import Language.Haskell.TH.Quote ()
import Language.Haskell.TH.Syntax ()
import Language.Haskell.TH.LanguageExtensions ()
#elif MIN_VERSION_template_haskell(2,11,0)
import Language.Haskell.TH ()
import Language.Haskell.TH.Lib ()
import Language.Haskell.TH.Ppr ()
import Language.Haskell.TH.PprLib ()
import Language.Haskell.TH.Quote ()
import Language.Haskell.TH.Syntax ()
import Language.Haskell.TH.LanguageExtensions ()
#elif MIN_VERSION_template_haskell(2,10,0)
import Language.Haskell.TH ()
import Language.Haskell.TH.Lib ()
import Language.Haskell.TH.Ppr ()
import Language.Haskell.TH.PprLib ()
import Language.Haskell.TH.Quote ()
import Language.Haskell.TH.Syntax ()
#elif MIN_VERSION_template_haskell(2,9,0)
import Language.Haskell.TH ()
import Language.Haskell.TH.Lib ()
import Language.Haskell.TH.Ppr ()
import Language.Haskell.TH.PprLib ()
import Language.Haskell.TH.Quote ()
import Language.Haskell.TH.Syntax ()
#elif MIN_VERSION_template_haskell(2,8,0)
import Language.Haskell.TH.Syntax ()
import Language.Haskell.TH.PprLib ()
import Language.Haskell.TH.Ppr ()
import Language.Haskell.TH.Lib ()
import Language.Haskell.TH.Quote ()
import Language.Haskell.TH ()
#elif MIN_VERSION_template_haskell(2,7,0)
import Language.Haskell.TH.Syntax.Internals ()
import Language.Haskell.TH.Syntax ()
import Language.Haskell.TH.PprLib ()
import Language.Haskell.TH.Ppr ()
import Language.Haskell.TH.Lib ()
import Language.Haskell.TH.Quote ()
import Language.Haskell.TH ()
#elif MIN_VERSION_template_haskell(2,6,0)
import Language.Haskell.TH.Syntax.Internals ()
import Language.Haskell.TH.Syntax ()
import Language.Haskell.TH.PprLib ()
import Language.Haskell.TH.Ppr ()
import Language.Haskell.TH.Lib ()
import Language.Haskell.TH.Quote ()
import Language.Haskell.TH ()
#elif MIN_VERSION_template_haskell(2,5,0)
import Language.Haskell.TH.Syntax.Internals ()
import Language.Haskell.TH.Syntax ()
import Language.Haskell.TH.PprLib ()
import Language.Haskell.TH.Ppr ()
import Language.Haskell.TH.Lib ()
import Language.Haskell.TH.Quote ()
import Language.Haskell.TH ()
#elif MIN_VERSION_template_haskell(2,4,0)
import Language.Haskell.TH.Syntax.Internals ()
import Language.Haskell.TH.Syntax ()
import Language.Haskell.TH.PprLib ()
import Language.Haskell.TH.Ppr ()
import Language.Haskell.TH.Lib ()
import Language.Haskell.TH.Quote ()
import Language.Haskell.TH ()
#elif MIN_VERSION_template_haskell(2,4,0)
import Language.Haskell.TH.Syntax.Internals ()
import Language.Haskell.TH.Syntax ()
import Language.Haskell.TH.PprLib ()
import Language.Haskell.TH.Ppr ()
import Language.Haskell.TH.Lib ()
import Language.Haskell.TH.Quote ()
import Language.Haskell.TH ()
#elif MIN_VERSION_template_haskell(2,3,0)
import Language.Haskell.TH.Syntax ()
import Language.Haskell.TH.PprLib ()
import Language.Haskell.TH.Ppr ()
import Language.Haskell.TH.Lib ()
import Language.Haskell.TH.Quote ()
import Language.Haskell.TH ()
#elif MIN_VERSION_template_haskell(2,3,0)
import Language.Haskell.TH.Syntax ()
import Language.Haskell.TH.PprLib ()
import Language.Haskell.TH.Ppr ()
import Language.Haskell.TH.Lib ()
import Language.Haskell.TH.Quote ()
import Language.Haskell.TH ()
#elif MIN_VERSION_template_haskell(2,2,0)
import Language.Haskell.TH.Syntax ()
import Language.Haskell.TH.PprLib ()
import Language.Haskell.TH.Ppr ()
import Language.Haskell.TH.Lib ()
import Language.Haskell.TH ()
#endif
#endif